# Generated by Django 5.2.1 on 2025-06-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_remove_answer_rating_tag_slug_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
